Algoritmo "senhafixa"

Var

senha , senhaCorreta : inteiro

Inicio

      senhaCorreta <- 2002
      
      escreval("Digite a senha : ")
      leia(senha)
      
      enquanto senha <> senhaCorreta faca
               escreval("Senha Invalida! Tente novamente : ")
               leia(senha)
      fimenquanto

		escreval("Acesso permitido")
		
Fimalgoritmo

//nao precisava usar outra variavel para armazenar o valor da senha





