Algoritmo "triangulo_area"

funcao area(x : real; y: real, z real): real

var
   a : inteiro

inicio

   a <- x + y
   retorne a * 10

fimfuncao

Var
x , med1,med2,med3, y, area : real


Inicio

      escreval("Entre com as medidas de X : ")
      para i de 0 ate x - 1 faca
          leia(x[i])
      fimpara
      
      escreval("Entre com as medidas de Y : ")
      para i de 0 ate x - 1 faca
          leia(y[i])
      fimpara





Fimalgoritmo