Algoritmo "consumo"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 

Var

distanciaTot, totalCombus : real

Inicio

escreva("Distancia percorrida: ")
leia(distanciaTot)
escreva("Combustivel gasto")
leia(totalCombus)
escreval
escreva("Consumo medio = ", distanciaTot/totalCombus:4:3)

Fimalgoritmo

//o exercicio esta coreto , porem poderia ter usado uma variavel para calcular
//o total de km por combustivel